id = "sobekneferu-zed-glory-theme"
name = "Sobekneferu Zed Glory"
version = "0.0.1"
schema_version = 1
authors = ["ramprasathmk <mkramprasath12@gmail.com>"]
description = "A custom dark theme for the Zed editor, built on top of the One Dark palette with hand-tuned modifications."
repository = "https://github.com/ramprasathmk/Sobekneferu-Zed-Glory"
