id = "ramprasathmk-theme"
name = "RamprasathMK Theme"
version = "0.0.1"
schema_version = 1
authors = ["RamprasathMK"]
description = "Super Duper Awesome Ramprasath Night Theme"
repository = "https://github.com/ramprasathmk/Sobekneferu-Zed-Glory"
